### PR TITLE
Add support for postcss.config.js

### LINKED ISSUE #1265: Add support for postcss.config.js
### Current Behavior

Adding custom postcss plugins can be done by extending webpack config, but it's not very convenient. Postcss starts to be first choice for next css rather than popular sass or less, checkout also https://tailwindcss.com/ 

### Desired Behavior

It's should be allowed to use custom config for postcss. Similar as it's done with `.babelrc`

### Suggested Solution

Add support for overriding default postcss config with .postcssrc.js or postcss.config.js 

### Who does this impact? Who is this for?

People who want to use next css future today!

### Describe alternatives you've considered

Extending webpack config.

### Additional context

There was a PR address this issue https://github.com/jaredpalmer/razzle/pull/521 but was closed as stale. Can fork it and push new. I thing we can manage to push it with next release. What do you think @nimaa77 ?

### PR DESCRIPTION
**Pull request by piecyk**
closes #1265

### CODE REVIEW

**Comment by nimaa77** [comment]
-.- oops

you have push changes to the next branch...

**Comment by nimaa77** [comment]
I think it's better to close this and open new PR

**Comment by piecyk** [comment]
Should be good 👍

**Comment by piecyk** [comment]
@nimaa77 Do we need still something else here ? IMHO ready for review 👍

**Comment by nimaa77** [comment]
I think this PR is ok

I will give it a look later today ...

**Review by nimaa77 — APPROVED** [review]

**Comment by nimaa77** [comment]
you are really a great coder

GG 🚀

**Pull request merged**
