### PR TITLE
Add Glamorous example

### PR DESCRIPTION
**Pull request by lucasterra**
Example with [Glamorous](https://github.com/paypal/glamorous) as the CSS-in-JS solution.

See `src/server.js` and `src/client.js` to see what is different from the basic implementation.

### CODE REVIEW

**Comment by lucasterra** [comment]
Done.

**Review by jaredpalmer — APPROVED** [review]

**Comment by lucasterra** [comment]
This got merged into `next`, was this the intended action? I had this PR opened before 2.0 was released. I can open a new one to master if needed.

**Comment by jaredpalmer** [comment]
Yeah I messed up.

**Comment by jaredpalmer** [comment]
Can you reope against master

**Comment by lucasterra** [comment]
Done. #668

**Pull request merged**
