### PR TITLE
Fix react loadable example

### PR DESCRIPTION
**Pull request by tkloht**
I noticed some problems with the react-loadable example.

First, when running the dev-server:
react-loadable tracks which chunks were required for the server-render, then we insert script-tags for these chunks. The problem when running on the dev-server is that these have to be loaded from `localhost:3001/static/js/1.chunk.js` (for example), instead of  just loading by relative path from `static/js/1.chunk.js`. With the current configuration the dev-server just returns index.html, instead of the js chunks, resulting in a parse error of course ("Uncaught SyntaxError: Unexpected token <")
I have simply changed the source of the script-tags for preloading to a absolute path to `http://${HOST}:${PORT}/${chunkname}`. If there is a better way to make this work please let me know :)

Second, for production:
The chunks were not loaded in the correct order.
We need to load the main bundle before the chunks, because the main bundle has all the "webpack-stuff" for loading the chunks. Loading the chunks before the main bundle results in error "Uncaught ReferenceError: webpackJsonp is not defined".
With the current setup the main bundle is loaded with defer, while the chunks are loaded without defer so they are loaded first, leading to the error.

I have removed the defer from the main bundle, this also reflects how the scripts are loaded in the react-loadable documentation.
I think it might also be possible to set the chunks to deferred loading, but:
- I am not sure if the order for loading the scripts is guaranteed when using defer. It seems to work as expected in chrome, i.e. deferred scripts load in the same order they are listed in the html. I have no idea if this is just coincidence  or how other browsers behave though.
- the react-loadable docs recommend to defer the hydration until all chunks are preloaded, see [here](https://github.com/thejameskyle/react-loadable/blob/f1bb24750ecc47864df8355f2ae69b42ea42035a/README.md#waiting-to-render-on-the-client-until-all-the-bundles-are-loaded) (also added in this PR). To my knowledge it is not possible to detect that all the chunks are loaded when using deferred loading, because you would use an inline script and that cannot run deferred. It would be possible to wait for all deferred scripts, but then you would also have to wait for all other scripts that you may be using.

I hope this makes sense, it is meant more as a bug report and call-for-help because i'm not entirely sure if there are better ways to fix these issues.

### CODE REVIEW

**Comment by jaredpalmer** [comment]
cc @thejameskyle 

How does react-loadable work or not work with `<script defer>`?

**Comment by jamiebuilds** [comment]
All the scripts need to be loaded before you call `window.main()`, it can work with `defer` if you somehow wait for them all to load.

**Comment by jamiebuilds** [comment]
Although I also would expect it to work as long as the main bundle is loaded ahead of time.

**Comment by tkloht** [comment]
do you mean just setting the main bundle and all chunks to defer? I tried that and it seems to work, although i don't quite understand why - wouldn't the main bundle execute before all the chunks are loaded? Or does the Loadable.preloadReady() take care of that?

**Comment by tkloht** [comment]
* forgot to say, I also removed the window.main() and just call Loadable.preloadReady directly

**Comment by jamiebuilds** [comment]
I don't think that Webpack does anything to guarantee the order of operations when loading bundles through script tags.

**Pull request merged**
