### PR TITLE
Add prefresh example to finch

### PR DESCRIPTION
**Pull request by JoviDeCroock**
In finch razzle seems to have a bug where it hard-requires React so the Preact example is broken, due to this bug I temp added React as a dependency. The odd one out is that the HMR-runtime used inside of razzle seems broken since it can never find the generated hot-update file.

### CODE REVIEW

**Comment by fivethreeo** [comment]
Do you know where React is hard required? Does HMR work in this example?

**Comment by JoviDeCroock** [comment]
HMR seems broken, HMR works on the original PR not on this one, will investigate later but not familiar with razzle-core yet.

**Comment by JoviDeCroock** [comment]
Seems to work correctly now, can't figure out what's hard-requiring React though.

**Comment by fivethreeo** [comment]
If you squash this into one commit and make the commit message "example: add preact prefresh example" i will merge it :)

**Pull request merged**
