### PR TITLE
Update with-loadable-components example

### PR DESCRIPTION
**Pull request by fivethreeo**
The recommended way for code splitting with ssr support until lazy and Suspense supports ssr is for the moment @loadable/component. Renamed example to with-loadable-component and removed with-react-loadable since it is now deprecated. Based off the v3.0.0-alpha.2 tag.

### CODE REVIEW

**Comment by fivethreeo** [comment]
Not stale

**Comment by nimaa77** [comment]
@fivethreeo I saw you have multiple pull requests on this project, please read #1159 and then send an email to Jared to get permission...

**Comment by fivethreeo** [comment]
Found a better example:

https://github.com/mbrochh/razzle-loadable-components

**Comment by fivethreeo** [comment]
Will do a new pull request, closing this.

**Pull request closed without merging**
