### PR TITLE
Updating examples with React 16

### PR DESCRIPTION
**Pull request by NickCis**
- [x] Updated react-* dependencies
- [x] Client side: `render` -> `hydrate`
- [ ] Update Typescript examples: *waiting for [react-dom](https://www.npmjs.com/package/@types/react-dom) update*

### CODE REVIEW

**Comment by jariz** [comment]
Nice!
Any idea on when will TS release types for 16?

**Comment by NickCis** [comment]
Types for react was just updated. I will update the example asap

Edit:

[React-dom types](https://www.npmjs.com/package/@types/react-dom) were not updated yet

**Comment by jaredpalmer** [comment]
For TS, let's just cast ReactDOM to `any` and call hydrate() 

```tsx
(ReactDOM as any).hydrate()
```

**Comment by jaredpalmer** [comment]
I'll fix TS

**Pull request merged**
