### PR TITLE
CSS Modules example

### PR DESCRIPTION
**Pull request by stereobooster**
PR for #428. It works, but `razzle.config.js` requires improvement

### CODE REVIEW

**Comment by stereobooster** [comment]
done

**Comment by JakeCooper** [comment]
:+1:

**Comment by alexparish** [comment]
This is awesome. Can it be merged? Seems like a useful example.

**Comment by mattlubner** [comment]
This already comes along with the base configuration, at least within `master`; you just need to name the CSS files as `<filename>.module.css`! 🙂

**Comment by alexparish** [comment]
Great stuff. Would be worth closing this PR and updating the documentation so other people can find that with ease.

**Comment by jaredpalmer** [comment]
@alexparish can you submit a new PR for the docs?

**Comment by alexparish** [comment]
@jaredpalmer sure I will do when I have a moment

**Comment by alexparish** [comment]
@jaredpalmer https://github.com/jaredpalmer/razzle/pull/694

**Pull request closed without merging**
