### PR TITLE
[Add - Example]: with "nanoexpress"

### PR DESCRIPTION
**Pull request by dalisoft**
This PR adds example of `razzle + nanoexpress` combo which in result will be faster response + quicker SSR

### CODE REVIEW

**Comment by dalisoft** [comment]
@jaredpalmer Can you look PR? I added example of nanoexpress (my backend library) + razzle combo

**Review by adaam2 — COMMENTED** [review]
The example looks fine, although I don't really see what value it adds as it is very similar to a standard express setup.

**Comment by dalisoft** [comment]
Hi and thanks for reply. 

This is similar to Express, but not same. There some things different and always having example is better than user searches. 

You may not merge, i just want add my library combo example, if possible.

**Comment by fivethreeo** [comment]
nanoexpress currently inactive and deprecated

**Pull request closed without merging**
