### PR TITLE
Add razzle-plugin-marko

### PR DESCRIPTION
**Pull request by fabrice8**
Hi Guys. I really love your work and really wanted to setup a MarkoJS application with Razzle but couldn't find any existing razzle-plugin for the configuration, so i cloned one of the plugins in the packages directory and adjusted it to support MarkoJS. I also added an example. Kindly check it out. Thank you.

### CODE REVIEW

**Comment by fivethreeo** [comment]
Can you change  it to use renderApp like here https://github.com/jaredpalmer/razzle/blob/master/examples/basic/src/server.js#L51 ?

**Comment by fivethreeo** [comment]
And follow https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit , see earlier razzle commits, not too strict so use your own judgement :)

**Comment by fivethreeo** [comment]
Some tips,

Don't add plugin as a submodule

```bash
git reset --soft rev-before-changes
# make sure plugin is not a submodule and change to renderApp
git commit -a -m "plugins: add razzle-plugin-marko with example"
```

**Comment by fabrice8** [comment]
> Some tips,
> 
> Don't add plugin as a submodule
> 
> ```shell
> git reset --soft rev-before-changes
> # make sure plugin is not a submodule and change to renderApp
> git commit -a -m "plugins: add razzle-plugin-marko with example"
> ```

**Comment by fabrice8** [comment]
Alright @fivethreeo . I'll follow your suggestions. Thanks for the feedback

**Comment by fabrice8** [comment]
> Can you change it to use renderApp like here https://github.com/jaredpalmer/razzle/blob/master/examples/basic/src/server.js#L51 ?

Okay. Just that rendering marko file with express kind of does things in a different way. I don't know whether you've tried it before. Anyway i'll give it a try and get back. Thanks

**Comment by fabrice8** [comment]
> Some tips,
> 
> Don't add plugin as a submodule
> 
> ```shell
> git reset --soft rev-before-changes
> # make sure plugin is not a submodule and change to renderApp
> git commit -a -m "plugins: add razzle-plugin-marko with example"
> ```

Thanks for the tip. Appreciate it

**Pull request closed without merging**
