### PR TITLE
promisify building/modifying configs and paths, add extra confighooks 

### PR DESCRIPTION
**Pull request by fivethreeo**

### CODE REVIEW

**Comment by fivethreeo** [comment]
Needs some fixing wrt. env and code readability. Possibly taking away unnecessary hooks or combining some hooks.

**Comment by nimaa77** [comment]
@fivethreeo I don't know why this is useful ... (it's lack of my knowledge)

but we can ask @jaredpalmer to have a review on this

**Comment by fivethreeo** [comment]
I am not quite happy with this solution yet. But the case for this is to allow async code to modify the config and the configOptions part is to avoid complex ways of changing simple things in the config already created, changing paths can be useful too. E.g. create ssl certificates before continuing the configuration. But the api is not quite the way I want it to be yet. Also it could be useful to have some hooks into createJestConfig.

**Comment by fivethreeo** [comment]
I'll ping when I have made some api changes. :)

**Comment by fivethreeo** [comment]
I'll close this and do it more incrementally, too many changes at once. I'll do asyc/await first. Then paths. Current idea adds more complexity and that is not what razzle is about.

**Pull request closed without merging**
