### PR TITLE
fix(scss-plugin): localIdentName deprecation

### LINKED ISSUE #1269: Unable to build application because `minimize` option is deprecated
### Current Behavior

When running `npm run build` in a project with `razzle-plugin-scss`, the build fails with the following error:

```
./src/App.scss
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'minimize'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esModule? }
```

### Expected behavior

App should build without errors.

### Reproducible example

Tested with `examples/with-scss`

### Suggested solution(s)

Removing `minimize: true` from `razzle-plugin-scss/index.js` fixes the error.

### PR DESCRIPTION
**Pull request by wei**
Breaking change in [css-loader 3.0.0](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#300-2019-06-11) requires `localIdentName` to be under `module` object {}. 

Current error message:
```
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'localIdentName'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esModule? }
```

This change has already been made in the main config:
https://github.com/jaredpalmer/razzle/blob/8905ab837167237f9d433de936e96530281d573d/packages/razzle/config/createConfig.js#L237-L243

This PR updates the same thing in **razzle-plugin-scss**

### CODE REVIEW

**Comment by wei** [comment]
@nimaa77 Did you want this line removed as part of this PR too?

https://github.com/jaredpalmer/razzle/blob/f65069989f9b55af2c1bc52ee5635587e095859b/packages/razzle-plugin-scss/index.js#L49

**Comment by nimaa77** [comment]
hey @wei  thanks for your contribution

what is the problem with that ` minimize: true, `? I saw somewhere that it's related to source maps

**Comment by wei** [comment]
My PR has nothing to do with `minimize: true`, it only touches `localIdentName`. I just saw you link #1269 to my PR and was wondering if you wanted both issues fixed in the same PR. 😄 I'll probably just let you fix #1269 so I don't step on your toes.

**Comment by nimaa77** [comment]
Let it be there I will double-check everything and if needed I will push some commits to your branch

Right now I'm busy on updating examples

**Comment by nimaa77** [comment]
there is a comment on the previous pull request
https://github.com/jaredpalmer/razzle/pull/1114#issuecomment-588896259

let's check and see if there is a bug with source maps or something

**Comment by wei** [comment]
> This needs to be set to true, otherwise production build fails when referencing imports using `resolve-url-loader`.

I could not reproduce this issue. 😃

**Review by nimaa77 — APPROVED** [review]

**Comment by nimaa77** [comment]
found something cool 
https://github.com/webpack-contrib/css-loader#pure-css-css-modules-and-postcss

```js
          {
            loader: 'css-loader',
            options: {
              // Run `postcss-loader` on each CSS `@import`, do not forget that `sass-loader` compile non CSS `@import`'s into a single file
              // If you need run `sass-loader` and `postcss-loader` on each CSS `@import` please set it to `2`
              importLoaders: 1,
              // Automatically enable css modules for files satisfying `/\.module\.\w+$/i` RegExp.
              modules: { auto: true }, // 👈 
            },
          },
```

**Comment by nimaa77** [comment]
I added a new example called, with `with-scss-modules` but it's not working
even `with-scss` example is not working when I link dependencies together

```bash
lerna bootstrap
cd packages/razzle-plugin-scss
yarn link
cd ../../examples/with-scss
yarn 
yarn link razzle-plugin-scss
yarn build
```
and it's not working maybe it has a problem with yarn link! (the same problem applies for `with-scss-modules` example)

**Comment by nimaa77** [comment]
I can't believe this the `scss` plugin implementation was broken (From a long time ago)

**Comment by fivethreeo** [comment]
I'll look into it. :)

**Comment by fivethreeo** [comment]
Thanks for bringing this to our attention. This has been fixed in another larger pull request. So this one unfortunately won’t be pulled 🙁 We appreciate the effort 😀

**Comment by wei** [comment]
@fivethreeo No worries, Could you link that PR here?

**Comment by fivethreeo** [comment]
Here, got a bit messy. 😀https://github.com/jaredpalmer/razzle/pull/1281

**Pull request closed without merging**
