### PR TITLE
Upgrade husky to 2.7

### PR DESCRIPTION
**Pull request by kkalavantavanich**
Upgrade husky to 2.7

### CODE REVIEW

**Comment by hennessyevan** [comment]
I think @greenkeeperio-bot has this one 👍 https://github.com/jaredpalmer/razzle/pull/1001

**Comment by kkalavantavanich** [comment]
I don't think so. The new format used in versions later than 0.14 is not changed with @greenkeeperio-bot .

**Comment by hennessyevan** [comment]
Ahhh you’re absolutely right, thanks. 🙌

**Comment by nimaa77** [comment]
thanks for your contribution.
at this moment that I'm reviewing this PR latest version of husky is 4.2.3
and I planned to update package dependencies

so I'm going to close this ❤️

**Pull request closed without merging**
