### PR TITLE
Next awesome

### PR DESCRIPTION
**Pull request by fivethreeo**
https://github.com/jaredpalmer/razzle/issues/1377

Simple instructions for testing the branch:

Install requirements and clone/check out the branch

```bash
git clone https://github.com/jaredpalmer/razzle
# or your fork
cd razzle
git checkout next-awesome

yarn install —dev

node -e 'require("./test/fixtures/util").setupStageWithExample("with-all-experimental", "with-all-experimental", symlink=false, yarnlink=true, install=true, test=false);'

cd with-all-experimental

yarn start
yarn build
yarn start:prod
yarn export
yarn start:static
yarn test

cd ..
node -e 'require("./test/fixtures/util").teardownStage("with-all-experimental");'
```

### CODE REVIEW

**Comment by hornta** [comment]
What's next awesome?

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/issues/1377

**Comment by benkingcode** [comment]
Can you break this down into more specific PRs? It's not clear what I'm looking at.

**Comment by fivethreeo** [comment]
Mostly it is theese three commits, with some other small fixes

https://github.com/jaredpalmer/razzle/pull/1378/commits/e169b1eea64851fc475f8f0c97047dfa7b376497
https://github.com/jaredpalmer/razzle/pull/1378/commits/6d91a4ec2d9b5a9e5f01e22a4fce21ab1a0adcce
https://github.com/jaredpalmer/razzle/pull/1378/commits/1336cd20fb9e5e63af26f3b6879c4d5abb6ced23

**Comment by benkingcode** [comment]
It's not really going to be feasible for anyone to review 82 changed files 😄 

It would be a lot easier if you opened specific PRs for each feature. Having one massive grab bag PR is unmanageable.

**Comment by fivethreeo** [comment]
I built all the features on top of each other, so hard to do something about that now. :|

**Pull request merged**
