### PR TITLE
Add PROTOCOL to .env

### LINKED ISSUE #503: Add PROTOCOL (http, https) to .env
http is hardcoded, allow to be a choice through .env

`process.env.PROTOCOL`: default `http`

### PR DESCRIPTION
**Pull request by dvdmgl**
Allow developer to specify protocol

Closes #503

### CODE REVIEW

**Comment by tesharp** [comment]
Any chance to get this merged in?

**Comment by jmca** [comment]
Can this be reopened and merged in?

**Comment by noeljackson** [comment]
Can’t things like this be a per-project addition, just using dotenv in proper locations instead of a razzle addition? This is what I’ve been doing for a while and it’s worked fine.

**Comment by jmca** [comment]
@noeljackson You are right, this can be worked around by using .env var and modified webpack config via razzle.config. This is what I've been doing up to this point, and it works, and it's not too much of a hassle (...sometimes). It just seems like one of the nice points of Razzle is to avoid these type of custom modifications. And since Razzle's internals use `process.env.PORT` and `process.env.HOST`, it seems odd that protocol is hard coded.

**Pull request closed without merging**
