### PR TITLE
Fixing an issue with unhandled error when the build config is invalid

### PR DESCRIPTION
**Pull request by iliyanyotov**
As per the title, fixing an issue that I encountered a few days ago when trying to use a custom Webpack config with errors that were swallowed by an empty catch block.

Currently doing the same check as in the start script in order to verify that the file is present before including it, and any errors will be captures and logged to the console.

I was using [this](https://github.com/iliyanyotov/razzle-webpack-unhandled-error) repository to debug and look for the problem.

### CODE REVIEW

**Comment by nimaa77** [comment]
WOW

**Comment by nimaa77** [comment]
I really impressed by `postinstall-postinstall` and `patch-package`.

nice job 👍

if you want, you can become a maintainer. just send an email to @jaredpalmer and ask him for privileges

**Comment by nimaa77** [comment]
can you fix the conflict :)
I change the target branch from master to next and ...

**Comment by iliyanyotov** [comment]
Yeah, I was experimenting with patch-package and it's an amazing tool.

Conflicts are now resolved. Keep up the good work on razzle with all the other contributors, will make sure to send an email to @jaredpalmer.

**Pull request merged**
