### PR TITLE
Add typescript after.js example

### PR DESCRIPTION
**Pull request by worudso**
It's `with-afterjs` + `with-typescript`.
Everything is working ok except `typings/index.d.ts`.
`typings/index.d.ts` seems to be ignored, then `react.svg` and `assets.json` cannot be recognized as typescript module(module declaration for "*.json" should be added). So the logo is not shown now. I think I made a stupid mistake but I can't find it. 
Also the type of `After` component is wrong. It doesn't allow `data` props. I tried to hack it and the conclusion is that it's because of `withRouter` component. I think you should force an explicit type for `After` than leaving it inferred by compiler(or fix `withRouter` type?).

### CODE REVIEW

**Comment by worudso** [comment]
I fixed logo bug. Now the type of `After` is the only problem.

**Comment by worudso** [comment]
https://github.com/jaredpalmer/after.js/issues/97 solves the `any` typing problem. I think everything is ok now.

**Comment by jaredpalmer** [comment]
Please remove package-lock.json's in another commit

**Comment by worudso** [comment]
No package-lock.json now.

**Comment by corydeppen** [comment]
Will this be merged soon, or are there things left to address?

**Comment by smkhalsa** [comment]
@jaredpalmer anything else holding this up? I'd also like to see this merged.

**Pull request closed without merging**
