### PR TITLE
Fix (razzle-dev-utils): make webpackHotDevClient work w/ webpack-dev-server v4

### PR DESCRIPTION
**Pull request by heath-freenome**
Fix (#1704) webpackHotDevClient for v4 by importing and using the two replacement APIs for the v3 `createSocketUrl` (i.e. `parseURL` and `createSocketURL`).

Also, because the created socket url for v4 is of the form `ws://<hostname/ws` create the connection using the browser native `WebSocket` API instead of `SocksJS`

### CODE REVIEW

**Comment by fivethreeo** [comment]
seems ok

**Comment by KrustyC** [comment]
Hi here, I am having some issues due to the old implementation, it looks as if this will fix it. Any update on when it will be released?

**Comment by fivethreeo** [comment]
@KrustyC released now

**Comment by KrustyC** [comment]
@fivethreeo that's amazing! Thanks a lot for the heads up!

**Pull request merged**
