### PR TITLE
Feature/scss plugin

### PR DESCRIPTION
**Pull request by jackjocross**
Cleaned up history from #663.

### CODE REVIEW

**Comment by rayandrew** [comment]
Looking good @crosscompile!

I have already checked it and all works perfectly!

Thank you for cleaning up the history, ready to merged I think.
Or is there anything left that needs to be implemented?

**Comment by nealoke** [comment]
Thanks for merging, just a question but can we use it from now on or are you waiting for other PR’s before releasing this?

**Comment by schoedav** [comment]
Thank's for implementing this plugin. I tested it and it works perfectly for me. Please release. If there is something missing I'd be glad to help.

**Comment by euchicosousa** [comment]
I got the example and it is not working

**Comment by SarKurd** [comment]
I need this so bad, is this released?

**Comment by kdubb1337** [comment]
@and3rsonsousa @SarKurd 
Follow the instructions to install the plugin based on the readme. Something like this:

```yarn add razzle-plugin-scss```

and then add it to your `razzle.config.js`:

```
module.exports = {
  plugins: ['scss'],
}
```

**Pull request merged**
